kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "opennavigator.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: |
    {{- tpl .Values.config . | nindent 4  }}