# Default values for opennavigator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  registry: ghcr.io
  repository: openinsight-proj/opennavigator
  tag: b7de005a5789d5d06c0ddb003f9bbc8892c3679c
  pullPolicy: IfNotPresent

config: |
  opAMPServer:
    network:
      host: 0.0.0.0
      port: 4320
      tlsSkipVerify: false
      tlsCert: /config/testdata/server_certs/server.cert.pem
      tlsKey: /config/testdata/server_certs/server.key.pem
      tlsCa: /config/testdata/certs/ca.cert.pem
  apiServer:
    network:
      host: 0.0.0.0
      port: 4200
      tlsSkipVerify: false
      tlsCert: /config/testdata/server_certs/server.cert.pem
      tlsKey: /config/testdata/server_certs/server.key.pem
      tlsCa: /config/testdata/certs/ca.cert.pem
  storage:
    type: mysql
    dsn: root:root@tcp({{ .Release.Name }}-mysql:3306)/opennavigator?charset=utf8mb4&parseTime=True&loc=Local&multiStatements=true
  telemetry:
    logging:
      level: info
      output: stdout

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}
podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  apiServerPort: 4200
  opAMPServerPort: 4320

resources:
   limits:
     cpu: 100m
     memory: 128Mi
   requests:
     cpu: 100m
     memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

mysql:
  enabled: true
  image:
    registry: docker.m.daocloud.io
    repository: mysql
    tag: 8.0.29
    pullPolicy: IfNotPresent
  password: root
  replicas: 1
  resources:
    limits:
      cpu: 1000m
      memory: 2000Mi
    requests:
      cpu: 100m
      memory: 200Mi
