apiVersion: v1
kind: Service
metadata:
  name: {{ include "opennavigator.fullname" . }}
  labels:
    {{- include "opennavigator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: opampserver
      targetPort: opampserver
      protocol: TCP
      port: {{ .Values.service.opAMPServerPort }}
    - name: apiserver
      targetPort: apiserver
      protocol: TCP
      port: {{ .Values.service.apiServerPort }}
  selector:
    {{- include "opennavigator.selectorLabels" . | nindent 4 }}
