apiVersion: v1
kind: Service
metadata:
  name: {{ include "opennavigator.fullname" . }}
  labels:
    {{- include "opennavigator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http-server
      targetPort: http-server
      protocol: TCP
      port: {{ .Values.service.serverPort }}
    - name: http-manager
      targetPort: http-manager
      protocol: TCP
      port: {{ .Values.service.managerPort }}
  selector:
    {{- include "opennavigator.selectorLabels" . | nindent 4 }}
